#!/bin/bash
# 'Worl' is an ASCII game written in bash about creating worlds and watching them go through life.

worl=~/.worl
worlds=$(echo $(ls $worl))
clear

function worldgen {
	
        read -rp "New world name: " world
        clear
	printf "Generating your world..."
	sleep 1

        while :; do
		
		clear
		printf "LOADING..."
		random=$((1 + RANDOM % 16))

		case $random in
		    1|2|3) printf "." >> $worl/$world.txt ;;
		    4|5) printf "T" >> $worl/$world.txt ;; 
		    6) printf "0" >> $worl/$world.txt ;;
		    7) printf "@" >> $worl/$world.txt ;;
		esac

		size=$(wc -m < $worl/$world.txt)
		clear
		printf "LOADING..."

		case $size in
			100|201|302|403|504|605|706|807|908) printf "\n" >> $worl/$world.txt ;;
			1009) printf "\n" >> $worl/world.txt && exec "$0" ;;
		esac

                continue
        break;
        done
}

if [[ -d $worl ]]; then
	if [[ $worlds = "" ]]; then
		worldgen
	else
		printf "List of worlds: \n\n" && ls $worl | sed -e 's/.txt//g' && printf "\n"
	        read -rp "Load world: " world
	        clear

		while :; do
			if [[ -f $worl/$world.txt ]]; then
			        printf "Current world: $world\n"
		       	 	cd $worl && printf "\n" && cat $world.txt && cd ~
				printf "\n\nType 'exit' to quit Worl or 'help' for a list of commands.\n" 
			else
				printf "There's no such world as '$world'!\n"
				sleep 2
				exec "$0"
			fi
		break;
		done

		while :; do
			read -rp "> " input
			if [[ $input = "exit" ]]; then
				clear
				printf "cya!\n\n"
				exit 1
			elif [[ $input = "help" ]]; then
				printf "\nexit - Exit Worl :(\nhelp - Show a list of commands.\nnew - Create a new world.\nload - Load a different world.\nclear - Clear the terminal.\ndel - Delete the current world.\n\n"
				continue 2
			elif  [[ $input = "new" ]]; then
				clear
				worldgen
			elif [[ $input = "load" ]]; then
				exec "$0"
			elif [[ $input = "clear" ]]; then
				clear
			        printf "Current world: $world\n"
		       	 	cd $worl && printf "\n" && cat $world.txt && cd ~
				printf "\n\nType 'exit' to quit Worl or 'help' for a list of commands.\n"
				continue 2
			elif [[ $input = "del" ]]; then
				rm $worl/$world.txt
				printf "\nWorld deleted!\n\n"
				printf "> "
				sleep 2
				exec "$0"
			else
				printf "\nCommand not found.\n\n"
				continue 2
			fi
		break;
		done
	fi
else
		mkdir $worl
		worldgen	
fi
